Repository harshAswani1109/demo-website, pull requests merged in 2023-08, with the labels that each got.

#1 assets added
  components/navbar/index.js
  public/assets/ansys.png
  public/assets/indian oil.png
  public/assets/proj.png
  public/assets/solid.png
Labels: enhancement

#4 landing page added
  app/page.js
  components/landing/index.js
  components/landing/more/index.js
  package.json
  public/next.svg
  public/vercel.svg
  yarn.lock
Labels: enhancement

#5 navbar fixed
  components/navbar/index.js
  package.json
  public/assets/logo1.png
  public/assets/logo2.png
Labels: enhancement

#6 add vision page
  app/globals.css
  app/vision/image1.jpg
  app/vision/layout.js
  app/vision/page.js
  tailwind.config.js
Labels: enhancement

#9 footer added
  .vscode/settings.json
  components/footer/index.js
Labels: documentation

#8 update
  app/about/page.js
  app/career/page.js
Labels: enhancement

#11 Rj/landing
  app/team/page.js
  components/footer/index.js
  components/landing/index.js
  components/landing/more/index.js
  components/navbar/index.js
  public/assets/logo3.png
Labels: bug, enhancement
